apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "admin-ui.nginx-config" . }}
  labels:
    app.kubernetes.io/name: {{ include "admin-ui.name" . }}
    helm.sh/chart: {{ include "admin-ui.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
    default.conf: |
        upstream api_storage {
            server    {{ template "admin-ui.kafkalot-storage.url" .}};
        }

        server {
            listen       80;
            server_name  localhost;

            root /usr/share/nginx/html;
            index index.html index.html;

            location / {
                try_files $uri $uri/ /index.html;
            }

            location ~ ^/(api) {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://api_storage;
            }
        }